<div class="container">
    <h1 class="h1"><?= $this->getPageTitle()?></h1>
    <form action="/post/store" method="post" accept-charset="utf-8">
        <div class="form-group">
            <label for="title">Título</label>
            <input type="text" name ="title" class="form-control">
        </div>
        <div class="form-group">
            <label for="title">Contéudo</label>
            <textarea name="content" rows="15" class="form-control"></textarea>
        </div>
        <a href="/posts" class="btn btn-default">Cancel</a>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>