<div class="container">
    <div class="row">
        <h1 class="h1">
        <?=$this->getPageTitle();?>
        <a href="/post/create" class="btn btn-primary pull-right">
        <i class="glyphicon glyphicon-plus-sign"></i>    New post 
        </a>
        </h1>
    </div>
    <div class="row">
        <?php foreach ($this->view->posts as $post): ?>
            <h3 class="h3">
                <a href="post/<?=$post->id?>/show"><?=$post->title;?></a>
            </h3>
           <p class="text-justify"><?=$post->content;?></p>
           <hr>
       <?php endforeach?>
    </div>
</div>